proxy:
  appserver:
    - boundarycommission.org.uk.lndo.site
    - ircommission.org.lndo.site

services:
  ircommission:
    type: solr:7
    portforward: true
    core: default
    config:
      dir: .lando/config/solr/7.x/default
